# For Java 8, try this
# FROM openjdk:8-jdk-alpine

# For Java 11, try this
FROM openjdk:17

# Refer to Maven build -> finalName
ARG JAR_FILE=JVM-Demo-JAVA17.jar

# cd /opt/app
WORKDIR /opt/app

# cp target/JVM-Demo-0.0.1-SNAPSHOT.jar /opt/app/app.jar
COPY ${JAR_FILE} app.jar

EXPOSE 9010

# java -jar /opt/app/app.jar
ENTRYPOINT ["java","-jar","app.jar","-XX:MaxRAMPercentage=60.0"]
